# Start from the official Golang image
FROM golang:1.19-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the application
RUN go build -o warehouse-service .

# Expose the port for the warehouse Service
EXPOSE 8084

# Start the warehouse Service
CMD ["./warehouse-service"]
