# Start from the official Golang image
FROM golang:1.19-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application code
COPY . .

# Build the application
RUN go build -o user-service .

# Expose the port for the user Service
EXPOSE 8081

# Start the user Service
CMD ["./user-service"]
